markdown:         kramdown
highlighter:      rouge
plugins:          [jekyll-paginate, jekyll-gist]


# Permalinks
permalink:           pretty

# Setup
title:               import dikshit
tagline:             Work In Progress
url:                 importdikshit.github.io
paginate:            1
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Ishan Dikshit
  email:             ishan.d@berkeley.edu

# Custom vars

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
