# Site settings
title: positively-semi-definite
description: "random notes on uncertainity"

author: ishan dikshit
email: ishan.d@berkeley.edu
twitter_username:
github_username: importdikshit

baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://importdikshit.github.io" # the base hostname & protocol for your site

google_analytics_id:
disqus_id: importdikshit-github-io

# Build settings
include: [_pages]
markdown: kramdown
permalink: /:year/:month/:title.html

sass:
    style: compressed

exclude: [vendor]
