name: importdikshit
description: >
    Work In Progress
about: >


master_repo: false
url: "importdikshit.github.io"
markdown: kramdown
highlighter: rouge

plugins: ['jekyll-paginate', 'jekyll-gist', 'jekyll-feed']

paginate: 50

rtl: false

owner:
  name:           importdikshit
