# Dependencies
markdown:         kramdown
highlighter:      rouge
plugins:          [jekyll-paginate]

# Permalinks
permalink:        pretty

# Setup
title:            'import dikshit'
tagline:          'Work in Progress'
description:      'The (n + 1)th attempt at creating and maintaining a Machine Learning blog'
url:              importdikshit.github.io
baseurl:          /

author:
  name:           'Ishan Dikshit'
  url:            importdikshit.github.io

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/importdikshit
