# Permalinks

permalink:           pretty

# Setup
title:               importdikshit
tagline:             'Work In Progress'
description:         'An imperfect, highly experimental advent into the land of Machine Learning blogging!'
url:                 importdikshit.github.com
baseurl:             ''
paginate:            1

# About/contact
author:
  name:              Ishan Dikshit
  url:               importdikshit.github.com
  email:             ishan.d@berkeley.edu

# Custom vars
version:             1.0.0
